### ISSUE TITLE
 ReferenceError: crypto is not defined

### ISSUE THREAD

**Issue by austinfrey** [webrecorder/warcio.js#15]
When attempting to use `WARCSerializar.create` in NodeJS, an error is thrown due to the `crypto` variable not being defined. It looks like the tests pass since the `@peculiar/crypto` module is used to set a [global crypto](https://github.com/webrecorder/warcio.js/blob/75c63b4bbd2c211c9922ca719cc7ffea8ecd4f2a/test/utils/index.js#L8) variable. Should I be doing that manually or could this module do that by default?

**Comment by ikreymer** [comment]
Ah, thanks for finding that! Yes, the module should do that by default, same as with Headers.
Should be fixed now in 1.3.1.
