### ISSUE TITLE
Puppeteer Example

### ISSUE THREAD

**Issue by jlarmstrongiv** [webrecorder/warcio.js#21]
Would love an example for generating a warc via puppeteer 😄

**Comment by jlarmstrongiv** [comment]
It appears capture methods are [explicitly](https://github.com/webrecorder/warcio.js#differences-from-node-warc) off the roadmap.  It is certainly possible to create a custom writer that follows the example in the [README](https://github.com/webrecorder/warcio.js#writing-warc-files) to work with puppeteer.  

There are two main ways to read/write warc files in NodeJS—[warcio.js](https://github.com/webrecorder/warcio.js) and [node-warc](https://github.com/N0taN3rd/node-warc).  

Between these two options, there will be differences in the metadata.  For example, warcio.js automatically includes the content and block hashes.  

However, neither of them entirely pass warc validation tests (from [warcat](https://github.com/chfoo/warcat) and [warctools](https://github.com/internetarchive/warctools)).  Both have content-length mismatches.  Though, `warcio.js` fails more tests.  

Subtle differences also mean that the [Unarchiver](https://theunarchiver.com/) app can only uncompress files from `node-warc`.  However, other tools such as [RelayWeb](https://github.com/webrecorder/replayweb.page) can open files from both libraries.

**Comment by ikreymer** [comment]
> However, neither of them entirely pass warc validation tests (from [warcat](https://github.com/chfoo/warcat) and [warctools](https://github.com/internetarchive/warctools)). Both have content-length mismatches. Though, `warcio.js` fails more tests.
> 
> Subtle differences also mean that the [Unarchiver](https://theunarchiver.com/) app can only uncompress files from `node-warc`. However, other tools such as [RelayWeb](https://github.com/webrecorder/replayweb.page) can open files from both libraries.

That's definitely something that should be fixed asap, if there's incorrect lengths, can you provide an example warc and open a new issue?

Yes, direct support for Puppeteer is out of scope in this library as this is supposed to be fairly low-level and also work in the browser, but can see about adding an example.

**Comment by jlarmstrongiv** [comment]
> Yes, direct support for Puppeteer is out of scope in this library as this is supposed to be fairly low-level and also work in the browser, but can see about adding an example.

No worries, I’ll go ahead and close this issue.  Thanks!
