### ISSUE TITLE
running example in browser leads to import error

### ISSUE THREAD

**Issue by msramalho** [webrecorder/warcio.js#67]
running [the first example](https://github.com/webrecorder/warcio.js#reading-warc-files) in the browser leads to an import error:

```
Uncaught TypeError: Failed to resolve module specifier "hash-wasm". 
Relative references must start with either "/", "./", or "../".
```

am I doing something wrong or is it an issue with https://cdn.jsdelivr.net/npm/warcio/dist/index.all.js?

**Comment by emma-sg** [comment]
From what I can tell, this (and #69) are due to some sort of misconfiguration of tsup, it seems to not be bundling to CJS correctly? Not sure if there's some settings for transforming imported modules or not
